/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // front matter
    'preface',
    'intro',
    {
      type: 'category',
      label: 'Part I',
      items: [
          'part1/p1-ch1-intro',
          'part1/p1-ch2-domain-model',
          'part1/p1-ch3-dto-models',
          'part1/p1-ch4-mapstruct',
      ],
    },
  ],
};

module.exports = sidebars;


// // // fullstack-book/sidebars.js
// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
// };
// module.exports = sidebars;